language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
  global:
    - PACKAGE=fiat-p256
    - DISTRO=alpine
  matrix:
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.05
    - OCAML_VERSION=4.06
    - OCAML_VERSION=4.07
    - OCAML_VERSION=4.08
